"CL-CK exception errors."

__all__ = [
    "ClCkControllerError",
]

class ClCkControllerError(Exception): ...
class ClCkGeneratorError(Exception): ...
class ClCkNameError(Exception): ...
class ClCkDuplicateError(Exception): ...