from clck.phonemes import (
    IPA_VOICED_BILABIAL_NASAL,
    IPA_VOICELESS_BILABIAL_PLOSIVE,
    IPA_VOICED_BILABIAL_PLOSIVE,
    IPA_VOICED_ALVEOLAR_NASAL,
    IPA_VOICELESS_ALVEOLAR_PLOSIVE,
    IPA_VOICED_ALVEOLAR_PLOSIVE,
    IPA_VOICELESS_ALVEOLAR_SIBILANTFRICATIVE,
    IPA_VOICED_ALVEOLAR_SIBILANTFRICATIVE,
    
    IPA_VOICED_VELAR_NASAL,
    IPA_VOICELESS_VELAR_PLOSIVE,
    IPA_VOICED_VELAR_PLOSIVE,
    IPA_VOICELESS_VELAR_NONSIBILANTFRICATIVE,
    IPA_VOICED_VELAR_NONSIBILANTFRICATIVE,

    IPA_VOICELESS_GLOTTAL_PLOSIVE
)

from clck.phonology import PhonologicalInventory



inventory: PhonologicalInventory = PhonologicalInventory(
    IPA_VOICED_BILABIAL_NASAL,
    IPA_VOICELESS_BILABIAL_PLOSIVE,
    IPA_VOICED_BILABIAL_PLOSIVE,
    IPA_VOICED_ALVEOLAR_NASAL,
    IPA_VOICELESS_ALVEOLAR_PLOSIVE,
    IPA_VOICED_ALVEOLAR_PLOSIVE,
    IPA_VOICELESS_ALVEOLAR_SIBILANTFRICATIVE,
    IPA_VOICED_ALVEOLAR_SIBILANTFRICATIVE,
    
    IPA_VOICED_VELAR_NASAL,
    IPA_VOICELESS_VELAR_PLOSIVE,
    IPA_VOICED_VELAR_PLOSIVE,
    IPA_VOICELESS_VELAR_NONSIBILANTFRICATIVE,
    IPA_VOICED_VELAR_NONSIBILANTFRICATIVE,

    IPA_VOICELESS_GLOTTAL_PLOSIVE
)

print(inventory.phonemes)