from .phonology import (
  IPA_Phoneme,
  IPA_Phoneme_NonpulmonicConsonant,
  IPA_Phoneme_PulmonicConsonant,
  IPA_Phoneme_Vowel
)



# VOWELS
IPA_CLOSE_FRONT_UNROUNDED_VOWEL: IPA_Phoneme                  = IPA_Phoneme_Vowel("i", "front", "close", False)
IPA_CLOSE_FRONT_ROUNDED_VOWEL: IPA_Phoneme                   = IPA_Phoneme_Vowel("i", "front", "close", True)
IPA_CLOSE_CENTRAL_UNROUNDED_VOWEL: IPA_Phoneme                = IPA_Phoneme_Vowel("", "central", "close", False)
IPA_CLOSE_CENTRAL_ROUNDED_VOWEL: IPA_Phoneme                 = IPA_Phoneme_Vowel("", "central", "close", True)
IPA_CLOSE_BACK_UNROUNDED_VOWEL: IPA_Phoneme                  = IPA_Phoneme_Vowel("", "back", "close", False)
IPA_CLOSE_BACK_ROUNDED_VOWEL: IPA_Phoneme                   = IPA_Phoneme_Vowel("", "back", "close", True)
IPA_NEARCLOSE_FRONT_UNROUNDED_VOWEL: IPA_Phoneme              = IPA_Phoneme_Vowel("", "front", "nearclose", False)
IPA_NEARCLOSE_FRONT_ROUNDED_VOWEL: IPA_Phoneme               = IPA_Phoneme_Vowel("", "front", "nearclose", True)
IPA_NEARCLOSE_BACK_ROUNDED_VOWEL: IPA_Phoneme                 = IPA_Phoneme_Vowel("", "back", "nearclose", True)
IPA_CLOSEMID_FRONT_UNROUNDED_VOWEL: IPA_Phoneme               = IPA_Phoneme_Vowel("", "front", "closemid", False)
IPA_CLOSEMID_FRONT_ROUNDED_VOWEL: IPA_Phoneme                = IPA_Phoneme_Vowel("", "front", "closemid", True)
IPA_CLOSEMID_CENTRAL_UNROUNDED_VOWEL: IPA_Phoneme             = IPA_Phoneme_Vowel("", "central", "closemid", False)
IPA_CLOSEMID_CENTRAL_ROUNDED_VOWEL: IPA_Phoneme              = IPA_Phoneme_Vowel("", "central", "closemid", True)
IPA_CLOSEMID_BACK_UNROUNDED_VOWEL: IPA_Phoneme                = IPA_Phoneme_Vowel("", "back", "closemid", False)
IPA_CLOSEMID_BACK_ROUNDED_VOWEL: IPA_Phoneme                 = IPA_Phoneme_Vowel("", "back", "closemid", True)
IPA_MID_FRONT_UNROUNDED_VOWEL: IPA_Phoneme                    = IPA_Phoneme_Vowel("", "front", "mid", False)
IPA_MID_FRONT_ROUNDED_VOWEL: IPA_Phoneme                     = IPA_Phoneme_Vowel("", "front", "mid", True)
IPA_MID_CENTRAL_VOWEL: IPA_Phoneme                            = IPA_Phoneme_Vowel("", "central", "mid", None)
IPA_MID_BACK_UNROUNDED_VOWEL: IPA_Phoneme                     = IPA_Phoneme_Vowel("", "back", "mid", False)
IPA_MID_BACK_ROUNDED_VOWEL: IPA_Phoneme                      = IPA_Phoneme_Vowel("", "back", "mid", True)
IPA_OPENMID_FRONT_UNROUNDED_VOWEL: IPA_Phoneme                = IPA_Phoneme_Vowel("", "front", "openmid", False)
IPA_OPENMID_FRONT_ROUNDED_VOWEL: IPA_Phoneme                  = IPA_Phoneme_Vowel("", "front", "openmid", True)
IPA_OPENMID_CENTRAL_UNROUNDED_VOWEL: IPA_Phoneme              = IPA_Phoneme_Vowel("", "central", "openmid", False)
IPA_OPENMID_CENTRAL_ROUNDED_VOWEL: IPA_Phoneme               = IPA_Phoneme_Vowel("", "central", "openmid", True)
IPA_OPENMID_BACK_UNROUNDED_VOWEL: IPA_Phoneme                 = IPA_Phoneme_Vowel("", "back", "openmid", False)
IPA_OPENMID_BACK_ROUNDED_VOWEL: IPA_Phoneme                   = IPA_Phoneme_Vowel("", "back", "openmid", True)
IPA_NEAROPEN_FRONT_UNROUNDED_VOWEL: IPA_Phoneme               = IPA_Phoneme_Vowel("", "front", "nearopen", False)
IPA_NEAROPEN_CENTRAL_VOWEL: IPA_Phoneme                       = IPA_Phoneme_Vowel("", "central", "nearopen", None)
IPA_OPEN_FRONT_UNROUNDED_VOWEL: IPA_Phoneme                   = IPA_Phoneme_Vowel("", "front", "open", False)
IPA_OPEN_FRONT_ROUNDED_VOWEL: IPA_Phoneme                     = IPA_Phoneme_Vowel("", "front", "open", True)
IPA_OPEN_CENTRAL_UNROUNDED_VOWEL: IPA_Phoneme                 = IPA_Phoneme_Vowel("", "central", "open", False)
IPA_OPEN_BACK_UNROUNDED_VOWEL: IPA_Phoneme                    = IPA_Phoneme_Vowel("", "back", "open", False)
IPA_OPEN_BACK_ROUNDED_VOWEL: IPA_Phoneme                      = IPA_Phoneme_Vowel("", "back", "open", True)

# PULMONIC CONSONANT NASALS
IPA_VOICELESS_BILABIAL_NASAL: IPA_Phoneme                     = IPA_Phoneme_PulmonicConsonant("m̥", "bilabial", "nasal", False)
IPA_VOICED_BILABIAL_NASAL: IPA_Phoneme                        = IPA_Phoneme_PulmonicConsonant("m", "bilabial", "nasal", True)
IPA_VOICED_LABIODENTAL_NASAL: IPA_Phoneme                     = IPA_Phoneme_PulmonicConsonant("ɱ", "labiodental", "nasal", True)
IPA_VOICED_LINGUOLABIAL_NASAL: IPA_Phoneme                    = IPA_Phoneme_PulmonicConsonant("n̼", "linguolabial", "nasal", True)
IPA_VOICELESS_ALVEOLAR_NASAL: IPA_Phoneme                     = IPA_Phoneme_PulmonicConsonant("n̥","alveolar", "nasal", False)
IPA_VOICED_ALVEOLAR_NASAL: IPA_Phoneme                        = IPA_Phoneme_PulmonicConsonant("n","alveolar", "nasal", True)
IPA_VOICELESS_RETROFLEX_NASAL: IPA_Phoneme                    = IPA_Phoneme_PulmonicConsonant("ɳ̊", "retroflex", "nasal", False)
IPA_VOICED_RETROFLEX_NASAL: IPA_Phoneme                       = IPA_Phoneme_PulmonicConsonant("ɳ", "retroflex", "nasal", True)
IPA_VOICELESS_PALATAL_NASAL: IPA_Phoneme                      = IPA_Phoneme_PulmonicConsonant("ɲ̊", "palatal", "nasal", False)
IPA_VOICED_PALATAL_NASAL: IPA_Phoneme                         = IPA_Phoneme_PulmonicConsonant("ɲ", "palatal", "nasal", True)
IPA_VOICELESS_VELAR_NASAL: IPA_Phoneme                        = IPA_Phoneme_PulmonicConsonant("ŋ̊", "velar", "nasal", False)
IPA_VOICED_VELAR_NASAL: IPA_Phoneme                           = IPA_Phoneme_PulmonicConsonant("ŋ", "velar", "nasal", True)
IPA_VOICED_UVULAR_NASAL: IPA_Phoneme                          = IPA_Phoneme_PulmonicConsonant("ɴ", "uvular", "nasal", True)

# PULMONIC CONSONANT PLOSIVES
IPA_VOICELESS_BILABIAL_PLOSIVE: IPA_Phoneme                   = IPA_Phoneme_PulmonicConsonant("p", "bilabial", "plosive", False)
IPA_VOICED_BILABIAL_PLOSIVE: IPA_Phoneme                      = IPA_Phoneme_PulmonicConsonant("b", "bilabial", "plosive", True)
IPA_VOICELESS_LABIODENTAL_PLOSIVE: IPA_Phoneme                = IPA_Phoneme_PulmonicConsonant("p̪", "labiodental", "plosive", False)
IPA_VOICED_LABIODENTAL_PLOSIVE: IPA_Phoneme                   = IPA_Phoneme_PulmonicConsonant("b̪", "labiodental", "plosive", True)
IPA_VOICELESS_LINGUOLABIAL_PLOSIVE: IPA_Phoneme               = IPA_Phoneme_PulmonicConsonant("t̼", "linguolabial", "plosive", False)
IPA_VOICED_LINGUOLABIAL_PLOSIVE: IPA_Phoneme                  = IPA_Phoneme_PulmonicConsonant("d̼", "linguolabial", "plosive", True)
IPA_VOICELESS_ALVEOLAR_PLOSIVE: IPA_Phoneme                   = IPA_Phoneme_PulmonicConsonant("t", "alveolar", "plosive", False)
IPA_VOICED_ALVEOLAR_PLOSIVE: IPA_Phoneme                      = IPA_Phoneme_PulmonicConsonant("d", "alveolar", "plosive", True)
IPA_VOICELESS_RETROFLEX_PLOSIVE: IPA_Phoneme                  = IPA_Phoneme_PulmonicConsonant("ʈ", "retroflex", "plosive", False)
IPA_VOICED_RETROFLEX_PLOSIVE: IPA_Phoneme                     = IPA_Phoneme_PulmonicConsonant("ɖ", "retroflex", "plosive", True)
IPA_VOICELESS_PALATAL_PLOSIVE: IPA_Phoneme                    = IPA_Phoneme_PulmonicConsonant("c", "palatal", "plosive", False)
IPA_VOICED_PALATAL_PLOSIVE: IPA_Phoneme                       = IPA_Phoneme_PulmonicConsonant("ɟ", "palatal", "plosive", True)
IPA_VOICELESS_VELAR_PLOSIVE: IPA_Phoneme                      = IPA_Phoneme_PulmonicConsonant("k", "velar", "plosive", False)
IPA_VOICED_VELAR_PLOSIVE: IPA_Phoneme                         = IPA_Phoneme_PulmonicConsonant("g", "velar", "plosive", True)
IPA_VOICELESS_UVULAR_PLOSIVE: IPA_Phoneme                     = IPA_Phoneme_PulmonicConsonant("q", "velar", "plosive", False)
IPA_VOICED_UVULAR_PLOSIVE: IPA_Phoneme                        = IPA_Phoneme_PulmonicConsonant("ɢ", "uvular", "plosive", True)
IPA_VOICELESS_EPIGLOTTAL_PLOSIVE: IPA_Phoneme                 = IPA_Phoneme_PulmonicConsonant("ʡ", "epiglottal", "plosive", False)
IPA_VOICELESS_GLOTTAL_PLOSIVE: IPA_Phoneme                    = IPA_Phoneme_PulmonicConsonant("ʔ", "glottal", "plosive", True)

# PULMONIC CONSONANT SIBILANT AFFRICATES
IPA_VOICELESS_ALVEOLAR_SIBILANTAFFRICATE: IPA_Phoneme         = IPA_Phoneme_PulmonicConsonant("", "alveolar", "sibilant affricate", False)
IPA_VOICED_ALVEOLAR_SIBILANTAFFRICATE: IPA_Phoneme            = IPA_Phoneme_PulmonicConsonant("", "alveolar", "sibilant affricate", True)
IPA_VOICELESS_POSTALVEOLAR_SIBILANTAFFRICATE: IPA_Phoneme     = IPA_Phoneme_PulmonicConsonant("", "postalveolar", "sibilant affricate", False)
IPA_VOICELESS_RETROFLEX_SIBILANTAFFRICATE: IPA_Phoneme        = IPA_Phoneme_PulmonicConsonant("", "retroflex", "sibilant affricate", False)
IPA_VOICED_RETROFLEX_SIBILANTAFFRICATE: IPA_Phoneme           = IPA_Phoneme_PulmonicConsonant("", "retroflex", "sibilant affricate", True)
IPA_VOICELESS_PALATAL_SIBILANTAFFRICATE: IPA_Phoneme          = IPA_Phoneme_PulmonicConsonant("", "palatal", "sibilant affricate", False)
IPA_VOICED_PALATAL_SIBILANTAFFRICATE: IPA_Phoneme             = IPA_Phoneme_PulmonicConsonant("", "palatal", "sibilant affricate", True)

# PULMONIC CONSONANT NONSIBILANT AFFRICATES
IPA_VOICELESS_BILABIAL_NONSIBILANTAFFRICATE: IPA_Phoneme      = IPA_Phoneme_PulmonicConsonant("", "bilabial", "nonsibilant affricate", False)
IPA_VOICED_BILABIAL_NONSIBILANTAFFRICATE: IPA_Phoneme         = IPA_Phoneme_PulmonicConsonant("", "bilabial", "nonsibilant affricate", True)
IPA_VOICELESS_LABIODENTAL_NONSIBILANTAFFRICATE: IPA_Phoneme   = IPA_Phoneme_PulmonicConsonant("", "labiodental", "nonsibilant affricate", False)
IPA_VOICED_LABIODENTAL_NONSIBILANTAFFRICATE: IPA_Phoneme      = IPA_Phoneme_PulmonicConsonant("", "labiodental", "nonsibilant affricate", True)
IPA_VOICELESS_DENTAL_NONSIBILANTAFFRICATE: IPA_Phoneme        = IPA_Phoneme_PulmonicConsonant("", "dental", "nonsibilant affricate", False)
IPA_VOICED_DENTAL_NONSIBILANTAFFRICATE: IPA_Phoneme           = IPA_Phoneme_PulmonicConsonant("", "dental", "nonsibilant affricate", True)
IPA_VOICELESS_ALVEOLAR_NONSIBILANTAFFRICATE: IPA_Phoneme      = IPA_Phoneme_PulmonicConsonant("", "alveolar", "nonsibilant affricate", False)
IPA_VOICED_ALVEOLAR_NONSIBILANTAFFRICATE: IPA_Phoneme         = IPA_Phoneme_PulmonicConsonant("", "alveolar", "nonsibilant affricate", True)
IPA_VOICELESS_POSTALVEOLAR_NONSIBILANTAFFRICATE: IPA_Phoneme  = IPA_Phoneme_PulmonicConsonant("", "postalveolar", "nonsibilant affricate", False)
IPA_VOICED_POSTALVEOLAR_NONSIBILANTAFFRICATE: IPA_Phoneme     = IPA_Phoneme_PulmonicConsonant("", "postalveolar", "nonsibilant affricate", True)
IPA_VOICELESS_PALATAL_NONSIBILANTAFFRICATE: IPA_Phoneme       = IPA_Phoneme_PulmonicConsonant("", "palatal", "nonsibilant affricate", False)
IPA_VOICED_PALATAL_NONSIBILANTAFFRICATE: IPA_Phoneme          = IPA_Phoneme_PulmonicConsonant("", "palatal", "nonsibilant affricate", True)
IPA_VOICELESS_VELAR_NONSIBILANTAFFRICATE: IPA_Phoneme         = IPA_Phoneme_PulmonicConsonant("", "velar", "nonsibilant affricate", False)
IPA_VOICED_VELAR_NONSIBILANTAFFRICATE: IPA_Phoneme            = IPA_Phoneme_PulmonicConsonant("", "velar", "nonsibilant affricate", True)
IPA_VOICELESS_UVULAR_NONSIBILANTAFFRICATE: IPA_Phoneme        = IPA_Phoneme_PulmonicConsonant("", "uvular", "nonsibilant affricate", False)
IPA_VOICED_UVULAR_NONSIBILANTAFFRICATE: IPA_Phoneme           = IPA_Phoneme_PulmonicConsonant("", "uvular", "nonsibilant affricate", True)
IPA_VOICELESS_EPIGLOTTAL_NONSIBILANTAFFRICATE: IPA_Phoneme    = IPA_Phoneme_PulmonicConsonant("", "epiglottal", "nonsibilant affricate", False)
IPA_VOICED_EPIGLOTTAL_NONSIBILANTAFFRICATE: IPA_Phoneme       = IPA_Phoneme_PulmonicConsonant("", "epiglottal", "nonsibilant affricate", True)
IPA_VOICELESS_GLOTTAL_NONSIBILANTAFFRICATE: IPA_Phoneme       = IPA_Phoneme_PulmonicConsonant("", "glottal", "nonsibilant affricate", False)

# PULMONIC CONSONANT SIBILANT FRICATIVES
IPA_VOICELESS_ALVEOLAR_SIBILANTFRICATIVE: IPA_Phoneme         = IPA_Phoneme_PulmonicConsonant("", "alveolar", "sibilant fricative", False)
IPA_VOICED_ALVEOLAR_SIBILANTFRICATIVE: IPA_Phoneme            = IPA_Phoneme_PulmonicConsonant("", "alveolar", "sibilant fricative", True)
IPA_VOICELESS_POSTALVEOLAR_SIBILANTFRICATIVE: IPA_Phoneme     = IPA_Phoneme_PulmonicConsonant("", "postalveolar", "sibilant fricative", False)
IPA_VOICED_POSTALVEOLAR_SIBILANTFRICATIVE: IPA_Phoneme        = IPA_Phoneme_PulmonicConsonant("", "postalveolar", "sibilant fricative", True)
IPA_VOICELESS_RETROFLEX_SIBILANTFRICATIVE: IPA_Phoneme        = IPA_Phoneme_PulmonicConsonant("", "retroflex", "sibilant fricative", False)
IPA_VOICED_RETROFLEX_SIBILANTFRICATIVE: IPA_Phoneme           = IPA_Phoneme_PulmonicConsonant("", "retroflex", "sibilant fricative", True)
IPA_VOICELESS_PALATAL_SIBILANTFRICATIVE: IPA_Phoneme          = IPA_Phoneme_PulmonicConsonant("", "palatal", "sibilant fricative", False)
IPA_VOICED_PALATAL_SIBILANTFRICATIVE: IPA_Phoneme             = IPA_Phoneme_PulmonicConsonant("", "palatal", "sibilant fricative", True)

# PULMONIC CONSONANT NONSIBILANT FRICATIVES
IPA_VOICELESS_BILABIAL_NONSIBILANTFRICATIVE: IPA_Phoneme      = IPA_Phoneme_PulmonicConsonant("", "bilabial", "nonsibilant fricative", False)
IPA_VOICED_BILABIAL_NONSIBILANTFRICATIVE: IPA_Phoneme         = IPA_Phoneme_PulmonicConsonant("", "bilabial", "nonsibilant fricative", True)
IPA_VOICELESS_LABIODENTAL_NONSIBILANTFRICATIVE: IPA_Phoneme   = IPA_Phoneme_PulmonicConsonant("", "labiodental", "nonsibilant fricative", False)
IPA_VOICED_LABIODENTAL_NONSIBILANTFRICATIVE: IPA_Phoneme      = IPA_Phoneme_PulmonicConsonant("", "labiodental", "nonsibilant fricative", True)
IPA_VOICELESS_LINGUOLABIAL_NONSIBILANTFRICATIVE: IPA_Phoneme  = IPA_Phoneme_PulmonicConsonant("", "linguolabial", "nonsibilant fricative", False)
IPA_VOICED_LINGUOLABIAL_NONSIBILANTFRICATIVE: IPA_Phoneme     = IPA_Phoneme_PulmonicConsonant("", "linguolabial", "nonsibilant fricative", True)
IPA_VOICELESS_DENTAL_NONSIBILANTFRICATIVE: IPA_Phoneme        = IPA_Phoneme_PulmonicConsonant("", "dental", "nonsibilant fricative", False)
IPA_VOICED_DENTAL_NONSIBILANTFRICATIVE: IPA_Phoneme           = IPA_Phoneme_PulmonicConsonant("", "dental", "nonsibilant fricative", True)
IPA_VOICELESS_ALVEOLAR_NONSIBILANTFRICATIVE: IPA_Phoneme      = IPA_Phoneme_PulmonicConsonant("", "alveolar", "nonsibilant fricative", False)
IPA_VOICED_ALVEOLAR_NONSIBILANTFRICATIVE: IPA_Phoneme         = IPA_Phoneme_PulmonicConsonant("", "alveolar", "nonsibilant fricative", True)
IPA_VOICELESS_POSTALVEOLAR_NONSIBILANTFRICATIVE: IPA_Phoneme  = IPA_Phoneme_PulmonicConsonant("", "postalveolar", "nonsibilant fricative", False)
IPA_VOICED_POSTALVEOLAR_NONSIBILANTFRICATIVE: IPA_Phoneme     = IPA_Phoneme_PulmonicConsonant("", "postalveolar", "nonsibilant fricative", True)
IPA_VOICELESS_RETROFLEX_NONSIBILANTFRICATIVE: IPA_Phoneme     = IPA_Phoneme_PulmonicConsonant("", "retroflex", "nonsibilant fricative", False)
IPA_VOICED_RETROFLEX_NONSIBILANTFRICATIVE: IPA_Phoneme        = IPA_Phoneme_PulmonicConsonant("", "retroflex", "nonsibilant fricative", True)
IPA_VOICELESS_PALATAL_NONSIBILANTFRICATIVE: IPA_Phoneme       = IPA_Phoneme_PulmonicConsonant("", "palatal", "nonsibilant fricative", False)
IPA_VOICED_PALATAL_NONSIBILANTFRICATIVE: IPA_Phoneme          = IPA_Phoneme_PulmonicConsonant("", "palatal", "nonsibilant fricative", True)
IPA_VOICELESS_VELAR_NONSIBILANTFRICATIVE: IPA_Phoneme         = IPA_Phoneme_PulmonicConsonant("", "velar", "nonsibilant fricative", False)
IPA_VOICED_VELAR_NONSIBILANTFRICATIVE: IPA_Phoneme            = IPA_Phoneme_PulmonicConsonant("", "velar", "nonsibilant fricative", True)
IPA_VOICELESS_EPIGLOTTAL_NONSIBILANTFRICATIVE: IPA_Phoneme    = IPA_Phoneme_PulmonicConsonant("", "epiglottal", "nonsibilant fricative", False)
IPA_VOICED_EPIGLOTTAL_NONSIBILANTFRICATIVE: IPA_Phoneme       = IPA_Phoneme_PulmonicConsonant("", "epiglottal", "nonsibilant fricative", True)
IPA_VOICELESS_GLOTTAL_NONSIBILANTFRICATIVE: IPA_Phoneme       = IPA_Phoneme_PulmonicConsonant("", "glottal", "nonsibilant fricative", False)
IPA_VOICED_GLOTTAL_NONSIBILANTFRICATIVE: IPA_Phoneme          = IPA_Phoneme_PulmonicConsonant("", "glottal", "nonsibilant fricative", True)

# PULMONIC CONSONANT APPROXIMANTS
IPA_VOICED_LABIODENTAL_APPROXIMANT: IPA_Phoneme               = IPA_Phoneme_PulmonicConsonant("", "labiodental", "approximant", True)
IPA_VOICED_ALVEOLAR_APPROXIMANT: IPA_Phoneme                  = IPA_Phoneme_PulmonicConsonant("", "alveolar", "approximant", True)
IPA_VOICED_RETROFLEX_APPROXIMANT: IPA_Phoneme                 = IPA_Phoneme_PulmonicConsonant("", "retroflex", "approximant", True)
IPA_VOICED_PALATAL_APPROXIMANT: IPA_Phoneme                   = IPA_Phoneme_PulmonicConsonant("", "palatal", "approximant", True)
IPA_VOICED_VELAR_APPROXIMANT: IPA_Phoneme                     = IPA_Phoneme_PulmonicConsonant("", "velar", "approximant", True)
IPA_VOICED_GLOTTAL_APPROXIMANT: IPA_Phoneme                   = IPA_Phoneme_PulmonicConsonant("", "glottal", "approximant", True)

# PULMONIC CONSONANT TAPS
IPA_VOICED_BILABIAL_TAP: IPA_Phoneme                          = IPA_Phoneme_PulmonicConsonant("", "bilabial", "tap", True)
IPA_VOICED_LABIODENTAL_TAP: IPA_Phoneme                       = IPA_Phoneme_PulmonicConsonant("", "labiodental", "tap", True)
IPA_VOICED_LINGUOLABIAL_TAP: IPA_Phoneme                      = IPA_Phoneme_PulmonicConsonant("", "linguolabial", "tap", True)
IPA_VOICELESS_ALVEOLAR_TAP: IPA_Phoneme                       = IPA_Phoneme_PulmonicConsonant("", "alveolar", "tap", True)
IPA_VOICED_ALVEOLAR_TAP: IPA_Phoneme                          = IPA_Phoneme_PulmonicConsonant("", "alveolar", "tap", True)
IPA_VOICED_UVULAR_TAP: IPA_Phoneme                            = IPA_Phoneme_PulmonicConsonant("", "uvular", "tap", True)
IPA_VOICED_EPIGLOTTAL_TAP: IPA_Phoneme                        = IPA_Phoneme_PulmonicConsonant("", "epiglottal", "tap", True)

# PULMONIC CONSONANT TRILLS
IPA_VOICELESS_BILABIAL_TRILL: IPA_Phoneme                     = IPA_Phoneme_PulmonicConsonant("", "bilabial", "trill", False)
IPA_VOICED_BILABIAL_TRILL: IPA_Phoneme                        = IPA_Phoneme_PulmonicConsonant("", "bilabial", "trill", True)
IPA_VOICELESS_ALVEOLAR_TRILL: IPA_Phoneme                     = IPA_Phoneme_PulmonicConsonant("", "alveolar", "trill", False)
IPA_VOICED_ALVEOLAR_TRILL: IPA_Phoneme                        = IPA_Phoneme_PulmonicConsonant("", "alveolar", "trill", True)
IPA_VOICELESS_RETROFLEX_TRILL: IPA_Phoneme                    = IPA_Phoneme_PulmonicConsonant("", "retroflex", "trill", False)
IPA_VOICED_RETROFLEX_TRILL: IPA_Phoneme                       = IPA_Phoneme_PulmonicConsonant("", "retroflex", "trill", True)
IPA_VOICELESS_UVULAR_TRILL: IPA_Phoneme                       = IPA_Phoneme_PulmonicConsonant("", "uvular", "trill", False)
IPA_VOICED_UVULAR_TRILL: IPA_Phoneme                          = IPA_Phoneme_PulmonicConsonant("", "uvular", "trill", True)
IPA_VOICELESS_EPIGLOTTAL_TRILL: IPA_Phoneme                   = IPA_Phoneme_PulmonicConsonant("", "epiglottal", "trill", False)
IPA_VOICED_EPIGLOTTAL_TRILL: IPA_Phoneme                      = IPA_Phoneme_PulmonicConsonant("", "epiglottal", "trill", True)

# PULMONIC CONSONANT LATERAL AFFRICATES
IPA_VOICELESS_ALVEOLAR_LATERALAFFRICATE: IPA_Phoneme          = IPA_Phoneme_PulmonicConsonant("", "alveolar", "lateral affricate", False)
IPA_VOICED_ALVEOLAR_LATERALAFFRICATE: IPA_Phoneme             = IPA_Phoneme_PulmonicConsonant("", "alveolar", "lateral affricate", True)
IPA_VOICELESS_RETROFLEX_LATERALAFFRICATE: IPA_Phoneme         = IPA_Phoneme_PulmonicConsonant("", "retroflex", "lateral affricate", False)
IPA_VOICED_RETROFLEX_LATERALAFFRICATE: IPA_Phoneme            = IPA_Phoneme_PulmonicConsonant("", "retroflex", "lateral affricate", True)
IPA_VOICELESS_PALATAL_LATERALAFFRICATE: IPA_Phoneme           = IPA_Phoneme_PulmonicConsonant("", "palatal", "lateral affricate", False)
IPA_VOICED_PALATAL_LATERALAFFRICATE: IPA_Phoneme              = IPA_Phoneme_PulmonicConsonant("", "palatal", "lateral affricate", True)
IPA_VOICELESS_VELAR_LATERALAFFRICATE: IPA_Phoneme             = IPA_Phoneme_PulmonicConsonant("", "velar", "lateral affricate", False)
IPA_VOICED_VELAR_LATERALAFFRICATE: IPA_Phoneme                = IPA_Phoneme_PulmonicConsonant("", "velar", "lateral affricate", True)

# PULMONIC CONSONANT LATERAL FRICATIVES
IPA_VOICELESS_ALVEOLAR_LATERALFRICATIVE: IPA_Phoneme          = IPA_Phoneme_PulmonicConsonant("", "alveolar", "lateral fricative", False)
IPA_VOICED_ALVEOLAR_LATERALFRICATIVE: IPA_Phoneme             = IPA_Phoneme_PulmonicConsonant("", "alveolar", "lateral fricative", True)
IPA_VOICELESS_RETROFLEX_LATERALFRICATIVE: IPA_Phoneme         = IPA_Phoneme_PulmonicConsonant("", "retroflex", "lateral fricative", False)
IPA_VOICED_RETROFLEX_LATERALFRICATIVE: IPA_Phoneme            = IPA_Phoneme_PulmonicConsonant("", "retroflex", "lateral fricative", True)
IPA_VOICELESS_PALATAL_LATERALFRICATIVE: IPA_Phoneme           = IPA_Phoneme_PulmonicConsonant("", "palatal", "lateral fricative", False)
IPA_VOICED_PALATAL_LATERALFRICATIVE: IPA_Phoneme              = IPA_Phoneme_PulmonicConsonant("", "palatal", "lateral fricative", True)
IPA_VOICELESS_VELAR_LATERALFRICATIVE: IPA_Phoneme             = IPA_Phoneme_PulmonicConsonant("", "velar", "lateral fricative", False)
IPA_VOICED_VELAR_LATERALFRICATIVE: IPA_Phoneme                = IPA_Phoneme_PulmonicConsonant("", "velar", "lateral fricative", True)

# PULMONIC CONSONANT LATERAL APPROXIMANTS
IPA_VOICED_ALVEOLAR_LATERALAPPROXIMANT: IPA_Phoneme           = IPA_Phoneme_PulmonicConsonant("", "alveolar", "lateral approximant", True)
IPA_VOICED_RETROFLEX_LATERALAPPROXIMANT: IPA_Phoneme          = IPA_Phoneme_PulmonicConsonant("", "retroflex", "lateral approximant", True)
IPA_VOICED_PALATAL_LATERALAPPROXIMANT: IPA_Phoneme            = IPA_Phoneme_PulmonicConsonant("", "palatal", "lateral approximant", True)
IPA_VOICED_VELAR_LATERALAPPROXIMANT: IPA_Phoneme              = IPA_Phoneme_PulmonicConsonant("", "velar", "lateral approximant", True)
IPA_VOICED_UVULAR_LATERALAPPROXIMANT: IPA_Phoneme             = IPA_Phoneme_PulmonicConsonant("", "uvular", "lateral approximant", True)

# PULMONIC CONSONANT LATERAL FLAPS
IPA_VOICELESS_ALVEOLAR_LATERALTAP: IPA_Phoneme                = IPA_Phoneme_PulmonicConsonant("", "alveolar", "lateral tap", False)
IPA_VOICED_ALVEOLAR_LATERALTAP: IPA_Phoneme                   = IPA_Phoneme_PulmonicConsonant("", "alveolar", "lateral tap", True)
IPA_VOICELESS_RETROFLEX_LATERALTAP: IPA_Phoneme               = IPA_Phoneme_PulmonicConsonant("", "retroflex", "lateral tap", False)
IPA_VOICED_RETROFLEX_LATERALTAP: IPA_Phoneme                  = IPA_Phoneme_PulmonicConsonant("", "retroflex", "lateral tap", True)
IPA_VOICED_PALATAL_LATERALTAP: IPA_Phoneme                    = IPA_Phoneme_PulmonicConsonant("", "palatal", "tap", True)
IPA_VOICED_VELAR_LATERALTAP: IPA_Phoneme                      = IPA_Phoneme_PulmonicConsonant("", "velar", "lateral tap", True)

# NONPULMONIC CONSONANT EJECTIVES - this section still needs to be added with
# more IPA phonemes according to the IPA chart of nonpulmonic consonants
IPA_BILABIAL_EJECTIVE_STOP: IPA_Phoneme                       = IPA_Phoneme_NonpulmonicConsonant("", "bilabial", "ejective stop")
IPA_ALVEOLAR_EJECTIVE_STOP: IPA_Phoneme                       = IPA_Phoneme_NonpulmonicConsonant("", "alveolar", "ejective stop")
IPA_RETROFLEX_EJECTIVE_STOP: IPA_Phoneme                      = IPA_Phoneme_NonpulmonicConsonant("", "retroflex", "ejective stop")
IPA_PALATAL_EJECTIVE_STOP: IPA_Phoneme                        = IPA_Phoneme_NonpulmonicConsonant("", "palatal", "ejective stop")
IPA_VELAR_EJECTIVE_STOP: IPA_Phoneme                          = IPA_Phoneme_NonpulmonicConsonant("", "velar", "ejective stop")
IPA_UVULAR_EJECTIVE_STOP: IPA_Phoneme                         = IPA_Phoneme_NonpulmonicConsonant("", "uvular", "ejective stop")
IPA_EPIGLOTTAL_EJECTIVE_STOP: IPA_Phoneme                     = IPA_Phoneme_NonpulmonicConsonant("", "epiglottal", "ejective stop")
IPA_DENTAL_EJECTIVE_AFFRICATE: IPA_Phoneme                    = IPA_Phoneme_NonpulmonicConsonant("", "dental", "ejective affricate")
IPA_ALVEOLAR_EJECTIVE_AFFRICATE: IPA_Phoneme                  = IPA_Phoneme_NonpulmonicConsonant("", "alveolar", "ejective affricate")