from .phonology import (
  IPA_Phoneme,
  IPA_Phoneme_PulmonicConsonant,
)


# PULMONIC CONSONANT NASALS
IPA_VOICELESS_BILABIAL_NASAL: IPA_Phoneme                     = IPA_Phoneme_PulmonicConsonant("", "bilabial", "nasal", False)
IPA_VOICED_BILABIAL_NASAL: IPA_Phoneme                        = IPA_Phoneme_PulmonicConsonant("", "bilabial", "nasal", True)
IPA_VOICED_LABIODENTAL_NASAL: IPA_Phoneme                     = IPA_Phoneme_PulmonicConsonant("", "labiodental", "nasal", True)
IPA_VOICED_LINGUOLABIAL_NASAL: IPA_Phoneme                    = IPA_Phoneme_PulmonicConsonant("", "linguolabial", "nasal", True)
IPA_VOICELESS_ALVEOLAR_NASAL: IPA_Phoneme                     = IPA_Phoneme_PulmonicConsonant("","alveolar", "nasal", False)
IPA_VOICED_ALVEOLAR_NASAL: IPA_Phoneme                        = IPA_Phoneme_PulmonicConsonant("","alveolar", "nasal", True)
IPA_VOICELESS_RETROFLEX_NASAL: IPA_Phoneme                    = IPA_Phoneme_PulmonicConsonant("", "retroflex", "nasal", False)
IPA_VOICED_RETROFLEX_NASAL: IPA_Phoneme                       = IPA_Phoneme_PulmonicConsonant("", "retroflex", "nasal", True)
IPA_VOICELESS_PALATAL_NASAL: IPA_Phoneme                      = IPA_Phoneme_PulmonicConsonant("", "palatal", "nasal", False)
IPA_VOICED_PALATAL_NASAL: IPA_Phoneme                         = IPA_Phoneme_PulmonicConsonant("", "palatal", "nasal", True)
IPA_VOICELESS_VELAR_NASAL: IPA_Phoneme                        = IPA_Phoneme_PulmonicConsonant("", "velar", "nasal", False)
IPA_VOICED_VELAR_NASAL: IPA_Phoneme                           = IPA_Phoneme_PulmonicConsonant("", "velar", "nasal", True)
IPA_VOICED_UVULAR_NASAL: IPA_Phoneme                          = IPA_Phoneme_PulmonicConsonant("", "uvular", "nasal", True)

# PULMONIC CONSONANT PLOSIVES
IPA_VOICELESS_BILABIAL_PLOSIVE: IPA_Phoneme                   = IPA_Phoneme_PulmonicConsonant("", "bilabial", "plosive", False)
IPA_VOICED_BILABIAL_PLOSIVE: IPA_Phoneme                      = IPA_Phoneme_PulmonicConsonant("", "bilabial", "plosive", True)
IPA_VOICELESS_LABIODENTAL_PLOSIVE: IPA_Phoneme                = IPA_Phoneme_PulmonicConsonant("", "labiodental", "plosive", False)
IPA_VOICED_LABIODENTAL_PLOSIVE: IPA_Phoneme                   = IPA_Phoneme_PulmonicConsonant("", "labiodental", "plosive", True)
IPA_VOICELESS_LINGUOLABIAL_PLOSIVE: IPA_Phoneme               = IPA_Phoneme_PulmonicConsonant("", "linguolabial", "plosive", False)
IPA_VOICED_LINGUOLABIAL_PLOSIVE: IPA_Phoneme                  = IPA_Phoneme_PulmonicConsonant("", "linguolabial", "plosive", True)
IPA_VOICELESS_ALVEOLAR_PLOSIVE: IPA_Phoneme                   = IPA_Phoneme_PulmonicConsonant("", "alveolar", "plosive", False)
IPA_VOICED_ALVEOLAR_PLOSIVE: IPA_Phoneme                      = IPA_Phoneme_PulmonicConsonant("", "alveolar", "plosive", True)
IPA_VOICELESS_RETROFLEX_PLOSIVE: IPA_Phoneme                  = IPA_Phoneme_PulmonicConsonant("", "retroflex", "plosive", False)
IPA_VOICED_RETROFLEX_PLOSIVE: IPA_Phoneme                     = IPA_Phoneme_PulmonicConsonant("", "retroflex", "plosive", True)
IPA_VOICELESS_PALATAL_PLOSIVE: IPA_Phoneme                    = IPA_Phoneme_PulmonicConsonant("", "palatal", "plosive", False)
IPA_VOICED_PALATAL_PLOSIVE: IPA_Phoneme                       = IPA_Phoneme_PulmonicConsonant("", "palatal", "plosive", True)
IPA_VOICELESS_VELAR_PLOSIVE: IPA_Phoneme                      = IPA_Phoneme_PulmonicConsonant("", "velar", "plosive", False)
IPA_VOICED_VELAR_PLOSIVE: IPA_Phoneme                         = IPA_Phoneme_PulmonicConsonant("", "velar", "plosive", True)
IPA_VOICELESS_UVULAR_PLOSIVE: IPA_Phoneme                     = IPA_Phoneme_PulmonicConsonant("", "velar", "plosive", False)
IPA_VOICED_UVULAR_PLOSIVE: IPA_Phoneme                        = IPA_Phoneme_PulmonicConsonant("", "uvular", "plosive", True)
IPA_VOICELESS_EPIGLOTTAL_PLOSIVE: IPA_Phoneme                 = IPA_Phoneme_PulmonicConsonant("", "epiglottal", "plosive", False)
IPA_VOICELESS_GLOTTAL_PLOSIVE: IPA_Phoneme                    = IPA_Phoneme_PulmonicConsonant("", "glottal", "plosive", True)

# PULMONIC CONSONANT SIBILANT AFFRICATES
IPA_VOICELESS_ALVEOLAR_SIBILANTAFFRICATE: IPA_Phoneme         = IPA_Phoneme_PulmonicConsonant("", "alveolar", "sibilant affricate", False)
IPA_VOICED_ALVEOLAR_SIBILANTAFFRICATE: IPA_Phoneme            = IPA_Phoneme_PulmonicConsonant("", "alveolar", "sibilant affricate", True)
IPA_VOICELESS_POSTALVEOLAR_SIBILANTAFFRICATE: IPA_Phoneme     = IPA_Phoneme_PulmonicConsonant("", "postalveolar", "sibilant affricate", False)
IPA_VOICELESS_RETROFLEX_SIBILANTAFFRICATE: IPA_Phoneme        = IPA_Phoneme_PulmonicConsonant("", "retroflex", "sibilant affricate", False)
IPA_VOICED_RETROFLEX_SIBILANTAFFRICATE: IPA_Phoneme           = IPA_Phoneme_PulmonicConsonant("", "retroflex", "sibilant affricate", True)
IPA_VOICELESS_PALATAL_SIBILANTAFFRICATE: IPA_Phoneme          = IPA_Phoneme_PulmonicConsonant("", "palatal", "sibilant affricate", False)
IPA_VOICED_PALATAL_SIBILANTAFFRICATE: IPA_Phoneme             = IPA_Phoneme_PulmonicConsonant("", "palatal", "sibilant affricate", True)

# PULMONIC CONSONANT NONSIBILANT AFFRICATES
IPA_VOICELESS_BILABIAL_NONSIBILANTAFFRICATE: IPA_Phoneme      = IPA_Phoneme_PulmonicConsonant("", "bilabial", "nonsibilant affricate", False)
IPA_VOICED_BILABIAL_NONSIBILANTAFFRICATE: IPA_Phoneme         = IPA_Phoneme_PulmonicConsonant("", "bilabial", "nonsibilant affricate", True)
IPA_VOICELESS_LABIODENTAL_NONSIBILANTAFFRICATE: IPA_Phoneme   = IPA_Phoneme_PulmonicConsonant("", "labiodental", "nonsibilant affricate", False)
IPA_VOICED_LABIODENTAL_NONSIBILANTAFFRICATE: IPA_Phoneme      = IPA_Phoneme_PulmonicConsonant("", "labiodental", "nonsibilant affricate", True)
IPA_VOICELESS_DENTAL_NONSIBILANTAFFRICATE: IPA_Phoneme        = IPA_Phoneme_PulmonicConsonant("", "dental", "nonsibilant affricate", False)
IPA_VOICED_DENTAL_NONSIBILANTAFFRICATE: IPA_Phoneme           = IPA_Phoneme_PulmonicConsonant("", "dental", "nonsibilant affricate", True)
IPA_VOICELESS_ALVEOLAR_NONSIBILANTAFFRICATE: IPA_Phoneme      = IPA_Phoneme_PulmonicConsonant("", "alveolar", "nonsibilant affricate", False)
IPA_VOICED_ALVEOLAR_NONSIBILANTAFFRICATE: IPA_Phoneme         = IPA_Phoneme_PulmonicConsonant("", "alveolar", "nonsibilant affricate", True)
IPA_VOICELESS_POSTALVEOLAR_NONSIBILANTAFFRICATE: IPA_Phoneme  = IPA_Phoneme_PulmonicConsonant("", "postalveolar", "nonsibilant affricate", False)
IPA_VOICED_POSTALVEOLAR_NONSIBILANTAFFRICATE: IPA_Phoneme     = IPA_Phoneme_PulmonicConsonant("", "postalveolar", "nonsibilant affricate", True)
IPA_VOICELESS_PALATAL_NONSIBILANTAFFRICATE: IPA_Phoneme       = IPA_Phoneme_PulmonicConsonant("", "palatal", "nonsibilant affricate", False)
IPA_VOICED_PALATAL_NONSIBILANTAFFRICATE: IPA_Phoneme          = IPA_Phoneme_PulmonicConsonant("", "palatal", "nonsibilant affricate", True)
IPA_VOICELESS_VELAR_NONSIBILANTAFFRICATE: IPA_Phoneme         = IPA_Phoneme_PulmonicConsonant("", "velar", "nonsibilant affricate", False)
IPA_VOICED_VELAR_NONSIBILANTAFFRICATE: IPA_Phoneme            = IPA_Phoneme_PulmonicConsonant("", "velar", "nonsibilant affricate", True)
IPA_VOICELESS_UVULAR_NONSIBILANTAFFRICATE: IPA_Phoneme        = IPA_Phoneme_PulmonicConsonant("", "uvular", "nonsibilant affricate", False)
IPA_VOICED_UVULAR_NONSIBILANTAFFRICATE: IPA_Phoneme           = IPA_Phoneme_PulmonicConsonant("", "uvular", "nonsibilant affricate", True)
IPA_VOICELESS_EPIGLOTTAL_NONSIBILANTAFFRICATE: IPA_Phoneme    = IPA_Phoneme_PulmonicConsonant("", "epiglottal", "nonsibilant affricate", False)
IPA_VOICED_EPIGLOTTAL_NONSIBILANTAFFRICATE: IPA_Phoneme       = IPA_Phoneme_PulmonicConsonant("", "epiglottal", "nonsibilant affricate", True)
IPA_VOICELESS_GLOTTAL_NONSIBILANTAFFRICATE: IPA_Phoneme       = IPA_Phoneme_PulmonicConsonant("", "glottal", "nonsibilant affricate", False)

# PULMONIC CONSONANT SIBILANT FRICATIVES
IPA_VOICELESS_ALVEOLAR_SIBILANTFRICATIVE: IPA_Phoneme         = IPA_Phoneme_PulmonicConsonant("", "alveolar", "sibilant fricative", False)
IPA_VOICED_ALVEOLAR_SIBILANTFRICATIVE: IPA_Phoneme            = IPA_Phoneme_PulmonicConsonant("", "alveolar", "sibilant fricative", True)
IPA_VOICELESS_POSTALVEOLAR_SIBILANTFRICATIVE: IPA_Phoneme     = IPA_Phoneme_PulmonicConsonant("", "postalveolar", "sibilant fricative", False)
IPA_VOICED_POSTALVEOLAR_SIBILANTFRICATIVE: IPA_Phoneme        = IPA_Phoneme_PulmonicConsonant("", "postalveolar", "sibilant fricative", True)
IPA_VOICELESS_RETROFLEX_SIBILANTFRICATIVE: IPA_Phoneme        = IPA_Phoneme_PulmonicConsonant("", "retroflex", "sibilant fricative", False)
IPA_VOICED_RETROFLEX_SIBILANTFRICATIVE: IPA_Phoneme           = IPA_Phoneme_PulmonicConsonant("", "retroflex", "sibilant fricative", True)
IPA_VOICELESS_PALATAL_SIBILANTFRICATIVE: IPA_Phoneme          = IPA_Phoneme_PulmonicConsonant("", "palatal", "sibilant fricative", False)
IPA_VOICED_PALATAL_SIBILANTFRICATIVE: IPA_Phoneme             = IPA_Phoneme_PulmonicConsonant("", "palatal", "sibilant fricative", True)

# PULMONIC CONSONANT NONSIBILANT FRICATIVES
IPA_VOICELESS_BILABIAL_NONSIBILANTFRICATIVE: IPA_Phoneme      = IPA_Phoneme_PulmonicConsonant("", "bilabial", "nonsibilant fricative", False)
IPA_VOICED_BILABIAL_NONSIBILANTFRICATIVE: IPA_Phoneme         = IPA_Phoneme_PulmonicConsonant("", "bilabial", "nonsibilant fricative", True)
IPA_VOICELESS_LABIODENTAL_NONSIBILANTFRICATIVE: IPA_Phoneme   = IPA_Phoneme_PulmonicConsonant("", "labiodental", "nonsibilant fricative", False)
IPA_VOICED_LABIODENTAL_NONSIBILANTFRICATIVE: IPA_Phoneme      = IPA_Phoneme_PulmonicConsonant("", "labiodental", "nonsibilant fricative", True)
IPA_VOICELESS_LINGUOLABIAL_NONSIBILANTFRICATIVE: IPA_Phoneme  = IPA_Phoneme_PulmonicConsonant("", "linguolabial", "nonsibilant fricative", False)
IPA_VOICED_LINGUOLABIAL_NONSIBILANTFRICATIVE: IPA_Phoneme     = IPA_Phoneme_PulmonicConsonant("", "linguolabial", "nonsibilant fricative", True)
IPA_VOICELESS_DENTAL_NONSIBILANTFRICATIVE: IPA_Phoneme        = IPA_Phoneme_PulmonicConsonant("", "dental", "nonsibilant fricative", False)
IPA_VOICED_DENTAL_NONSIBILANTFRICATIVE: IPA_Phoneme           = IPA_Phoneme_PulmonicConsonant("", "dental", "nonsibilant fricative", True)
IPA_VOICELESS_ALVEOLAR_NONSIBILANTFRICATIVE: IPA_Phoneme      = IPA_Phoneme_PulmonicConsonant("", "alveolar", "nonsibilant fricative", False)
IPA_VOICED_ALVEOLAR_NONSIBILANTFRICATIVE: IPA_Phoneme         = IPA_Phoneme_PulmonicConsonant("", "alveolar", "nonsibilant fricative", True)
IPA_VOICELESS_POSTALVEOLAR_NONSIBILANTFRICATIVE: IPA_Phoneme  = IPA_Phoneme_PulmonicConsonant("", "postalveolar", "nonsibilant fricative", False)
IPA_VOICED_POSTALVEOLAR_NONSIBILANTFRICATIVE: IPA_Phoneme     = IPA_Phoneme_PulmonicConsonant("", "postalveolar", "nonsibilant fricative", True)
IPA_VOICELESS_RETROFLEX_NONSIBILANTFRICATIVE: IPA_Phoneme     = IPA_Phoneme_PulmonicConsonant("", "retroflex", "nonsibilant fricative", False)
IPA_VOICED_RETROFLEX_NONSIBILANTFRICATIVE: IPA_Phoneme        = IPA_Phoneme_PulmonicConsonant("", "retroflex", "nonsibilant fricative", True)
IPA_VOICELESS_PALATAL_NONSIBILANTFRICATIVE: IPA_Phoneme       = IPA_Phoneme_PulmonicConsonant("", "palatal", "nonsibilant fricative", False)
IPA_VOICED_PALATAL_NONSIBILANTFRICATIVE: IPA_Phoneme          = IPA_Phoneme_PulmonicConsonant("", "palatal", "nonsibilant fricative", True)
IPA_VOICELESS_VELAR_NONSIBILANTFRICATIVE: IPA_Phoneme         = IPA_Phoneme_PulmonicConsonant("", "velar", "nonsibilant fricative", False)
IPA_VOICED_VELAR_NONSIBILANTFRICATIVE: IPA_Phoneme            = IPA_Phoneme_PulmonicConsonant("", "velar", "nonsibilant fricative", True)
IPA_VOICELESS_EPIGLOTTAL_NONSIBILANTFRICATIVE: IPA_Phoneme    = IPA_Phoneme_PulmonicConsonant("", "epiglottal", "nonsibilant fricative", False)
IPA_VOICED_EPIGLOTTAL_NONSIBILANTFRICATIVE: IPA_Phoneme       = IPA_Phoneme_PulmonicConsonant("", "epiglottal", "nonsibilant fricative", True)
IPA_VOICELESS_GLOTTAL_NONSIBILANTFRICATIVE: IPA_Phoneme       = IPA_Phoneme_PulmonicConsonant("", "glottal", "nonsibilant fricative", False)
IPA_VOICED_GLOTTAL_NONSIBILANTFRICATIVE: IPA_Phoneme          = IPA_Phoneme_PulmonicConsonant("", "glottal", "nonsibilant fricative", True)